using Ceiba.Core.Entities;
using Ceiba.Core.Interfaces;
using Ceiba.Infrastructure.Data;
using Ceiba.Infrastructure.Services;
using Ceiba.Shared.DTOs;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Moq;
using System.Text.Json;

namespace Ceiba.Application.Tests.Services;

/// <summary>
/// Unit tests for AutomatedReportService.
/// US4: Reportes Automatizados Diarios con IA.
/// Tests T084: Automated report generation, templates, and statistics.
/// </summary>
public class AutomatedReportServiceTests : IDisposable
{
    private readonly CeibaDbContext _context;
    private readonly Mock<IAiNarrativeService> _mockAiService;
    private readonly Mock<IEmailService> _mockEmailService;
    private readonly Mock<IAuditService> _mockAuditService;
    private readonly Mock<IConfiguration> _mockConfiguration;
    private readonly Mock<ILogger<AutomatedReportService>> _mockLogger;

    /// <summary>
    /// JSON options matching those used in AutomatedReportService for consistent serialization.
    /// </summary>
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true
    };

    public AutomatedReportServiceTests()
    {
        var options = new DbContextOptionsBuilder<CeibaDbContext>()
            .UseInMemoryDatabase(databaseName: $"AutomatedReportTests_{Guid.NewGuid()}")
            .Options;

        _context = new CeibaDbContext(options);
        _mockAiService = new Mock<IAiNarrativeService>();
        _mockEmailService = new Mock<IEmailService>();
        _mockAuditService = new Mock<IAuditService>();
        _mockConfiguration = new Mock<IConfiguration>();
        _mockLogger = new Mock<ILogger<AutomatedReportService>>();

        SetupDefaultMocks();
    }

    public void Dispose()
    {
        _context.Dispose();
    }

    private void SetupDefaultMocks()
    {
        _mockAiService.Setup(s => s.GenerateNarrativeAsync(
                It.IsAny<NarrativeRequestDto>(),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(new NarrativeResponseDto
            {
                Success = true,
                Narrativa = "Test narrative generated by AI",
                TokensUsed = 100
            });

        _mockEmailService.Setup(s => s.SendAsync(
                It.IsAny<SendEmailRequestDto>(),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(new SendEmailResultDto
            {
                Success = true,
                SentAt = DateTime.UtcNow
            });

        _mockAuditService.Setup(s => s.LogAsync(
                It.IsAny<string>(),
                It.IsAny<int?>(),
                It.IsAny<string>(),
                It.IsAny<string?>(),
                It.IsAny<string?>(),
                It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);
    }

    private AutomatedReportService CreateService()
    {
        return new AutomatedReportService(
            _context,
            _mockAiService.Object,
            _mockEmailService.Object,
            _mockAuditService.Object,
            _mockConfiguration.Object,
            _mockLogger.Object);
    }

    /// <summary>
    /// Creates a mock IConfigurationSection that simulates a list of strings.
    /// This is needed because Moq cannot mock extension methods like Get&lt;T&gt;().
    /// The Get&lt;List&lt;string&gt;&gt;() extension method works by iterating GetChildren().
    /// </summary>
    private static Mock<IConfigurationSection> CreateMockListSection(List<string>? values)
    {
        var mockSection = new Mock<IConfigurationSection>();

        if (values == null || values.Count == 0)
        {
            mockSection.Setup(s => s.GetChildren()).Returns(Array.Empty<IConfigurationSection>());
            return mockSection;
        }

        var children = values.Select((value, index) =>
        {
            var childMock = new Mock<IConfigurationSection>();
            childMock.Setup(c => c.Key).Returns(index.ToString());
            childMock.Setup(c => c.Value).Returns(value);
            childMock.Setup(c => c.Path).Returns($"AutomatedReports:Recipients:{index}");
            return childMock.Object;
        }).ToList();

        mockSection.Setup(s => s.GetChildren()).Returns(children);

        return mockSection;
    }

    private async Task<Zona> CreateTestZona(string nombre = "Zona Test")
    {
        var zona = new Zona { Nombre = nombre, Activo = true };
        _context.Zonas.Add(zona);
        await _context.SaveChangesAsync();
        return zona;
    }

    private async Task<ReporteIncidencia> CreateTestReport(
        short estado = 1,
        Zona? zona = null,
        string delito = "Test Delito",
        int edad = 30)
    {
        var report = new ReporteIncidencia
        {
            HechosReportados = "Test hechos",
            AccionesRealizadas = "Test acciones",
            Delito = delito,
            Estado = estado,
            Sexo = "Mujer",
            Edad = edad,
            TipoDeAtencion = "Presencial",
            TipoDeAccion = "Preventiva",
            Zona = zona!,
            LgbtttiqPlus = false,
            Migrante = false,
            SituacionCalle = false,
            Discapacidad = false,
            Traslados = "No",
            CreatedAt = DateTime.UtcNow
        };
        _context.ReportesIncidencia.Add(report);
        await _context.SaveChangesAsync();
        return report;
    }

    #region GetReportsAsync Tests

    [Fact(DisplayName = "T084: GetReportsAsync should return empty list when no reports exist")]
    public async Task GetReportsAsync_NoReports_ReturnsEmptyList()
    {
        // Arrange
        var service = CreateService();

        // Act
        var result = await service.GetReportsAsync();

        // Assert
        result.Should().BeEmpty();
    }

    [Fact(DisplayName = "T084: GetReportsAsync should return reports ordered by CreatedAt desc")]
    public async Task GetReportsAsync_MultipleReports_ReturnsOrderedByCreatedAtDesc()
    {
        // Arrange
        var oldReport = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow.AddDays(-3),
            FechaFin = DateTime.UtcNow.AddDays(-2),
            ContenidoMarkdown = "Old report",
            Estadisticas = "{}",
            CreatedAt = DateTime.UtcNow.AddDays(-2)
        };

        var newReport = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow.AddDays(-1),
            FechaFin = DateTime.UtcNow,
            ContenidoMarkdown = "New report",
            Estadisticas = "{}",
            CreatedAt = DateTime.UtcNow
        };

        _context.ReportesAutomatizados.AddRange(oldReport, newReport);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.GetReportsAsync();

        // Assert
        result.Should().HaveCount(2);
        result[0].CreatedAt.Should().BeAfter(result[1].CreatedAt);
    }

    [Fact(DisplayName = "T084: GetReportsAsync should filter by fechaDesde")]
    public async Task GetReportsAsync_FilterByFechaDesde_ReturnsFilteredResults()
    {
        // Arrange
        var oldReport = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow.AddDays(-10),
            FechaFin = DateTime.UtcNow.AddDays(-9),
            ContenidoMarkdown = "Old report",
            Estadisticas = "{}",
            CreatedAt = DateTime.UtcNow.AddDays(-10)
        };

        var newReport = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow.AddDays(-1),
            FechaFin = DateTime.UtcNow,
            ContenidoMarkdown = "New report",
            Estadisticas = "{}",
            CreatedAt = DateTime.UtcNow
        };

        _context.ReportesAutomatizados.AddRange(oldReport, newReport);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.GetReportsAsync(fechaDesde: DateTime.UtcNow.AddDays(-2));

        // Assert
        result.Should().HaveCount(1);
        // New report is the one that matches fechaDesde filter
    }

    [Fact(DisplayName = "T084: GetReportsAsync should filter by enviado status")]
    public async Task GetReportsAsync_FilterByEnviado_ReturnsFilteredResults()
    {
        // Arrange
        var sentReport = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow.AddDays(-1),
            FechaFin = DateTime.UtcNow,
            ContenidoMarkdown = "Sent report",
            Estadisticas = "{}",
            Enviado = true,
            FechaEnvio = DateTime.UtcNow
        };

        var unsentReport = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow.AddDays(-1),
            FechaFin = DateTime.UtcNow,
            ContenidoMarkdown = "Unsent report",
            Estadisticas = "{}",
            Enviado = false
        };

        _context.ReportesAutomatizados.AddRange(sentReport, unsentReport);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var resultSent = await service.GetReportsAsync(enviado: true);
        var resultUnsent = await service.GetReportsAsync(enviado: false);

        // Assert
        resultSent.Should().HaveCount(1);
        resultSent[0].Enviado.Should().BeTrue();
        resultUnsent.Should().HaveCount(1);
        resultUnsent[0].Enviado.Should().BeFalse();
    }

    [Fact(DisplayName = "T084: GetReportsAsync should respect pagination")]
    public async Task GetReportsAsync_Pagination_ReturnsCorrectPage()
    {
        // Arrange
        for (int i = 0; i < 5; i++)
        {
            _context.ReportesAutomatizados.Add(new ReporteAutomatizado
            {
                FechaInicio = DateTime.UtcNow.AddDays(-i - 1),
                FechaFin = DateTime.UtcNow.AddDays(-i),
                ContenidoMarkdown = $"Report {i}",
                Estadisticas = "{}",
                CreatedAt = DateTime.UtcNow.AddDays(-i)
            });
        }
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var page1 = await service.GetReportsAsync(skip: 0, take: 2);
        var page2 = await service.GetReportsAsync(skip: 2, take: 2);

        // Assert
        page1.Should().HaveCount(2);
        page2.Should().HaveCount(2);
    }

    #endregion

    #region GetReportByIdAsync Tests

    [Fact(DisplayName = "T084: GetReportByIdAsync should return null when report not found")]
    public async Task GetReportByIdAsync_NotFound_ReturnsNull()
    {
        // Arrange
        var service = CreateService();

        // Act
        var result = await service.GetReportByIdAsync(999);

        // Assert
        result.Should().BeNull();
    }

    [Fact(DisplayName = "T084: GetReportByIdAsync should return report detail when found")]
    public async Task GetReportByIdAsync_Found_ReturnsDetail()
    {
        // Arrange
        // Use JsonOptions to match the service's serialization format (camelCase)
        var report = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow.AddDays(-1),
            FechaFin = DateTime.UtcNow,
            ContenidoMarkdown = "# Test Report",
            Estadisticas = JsonSerializer.Serialize(new ReportStatisticsDto { TotalReportes = 10 }, JsonOptions)
        };
        _context.ReportesAutomatizados.Add(report);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.GetReportByIdAsync(report.Id);

        // Assert
        result.Should().NotBeNull();
        result!.Id.Should().Be(report.Id);
        result.ContenidoMarkdown.Should().Be("# Test Report");
        result.Estadisticas.TotalReportes.Should().Be(10);
    }

    #endregion

    #region Templates Tests

    [Fact(DisplayName = "T084: GetTemplatesAsync should return only active templates by default")]
    public async Task GetTemplatesAsync_Default_ReturnsOnlyActive()
    {
        // Arrange
        var activeTemplate = new ModeloReporte
        {
            Nombre = "Active Template",
            ContenidoMarkdown = "# Active",
            Activo = true
        };

        var inactiveTemplate = new ModeloReporte
        {
            Nombre = "Inactive Template",
            ContenidoMarkdown = "# Inactive",
            Activo = false
        };

        _context.ModelosReporte.AddRange(activeTemplate, inactiveTemplate);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.GetTemplatesAsync();

        // Assert
        result.Should().HaveCount(1);
        result[0].Activo.Should().BeTrue();
    }

    [Fact(DisplayName = "T084: GetTemplatesAsync should return all templates when includeInactive is true")]
    public async Task GetTemplatesAsync_IncludeInactive_ReturnsAll()
    {
        // Arrange
        _context.ModelosReporte.AddRange(
            new ModeloReporte { Nombre = "Active", ContenidoMarkdown = "#", Activo = true },
            new ModeloReporte { Nombre = "Inactive", ContenidoMarkdown = "#", Activo = false }
        );
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.GetTemplatesAsync(includeInactive: true);

        // Assert
        result.Should().HaveCount(2);
    }

    [Fact(DisplayName = "T084: GetTemplateByIdAsync should return template when found")]
    public async Task GetTemplateByIdAsync_Found_ReturnsTemplate()
    {
        // Arrange
        var template = new ModeloReporte
        {
            Nombre = "Test Template",
            Descripcion = "Description",
            ContenidoMarkdown = "# Content",
            Activo = true,
            EsDefault = false
        };
        _context.ModelosReporte.Add(template);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.GetTemplateByIdAsync(template.Id);

        // Assert
        result.Should().NotBeNull();
        result!.Nombre.Should().Be("Test Template");
        result.Descripcion.Should().Be("Description");
        result.ContenidoMarkdown.Should().Be("# Content");
    }

    [Fact(DisplayName = "T084: GetDefaultTemplateAsync should return default template")]
    public async Task GetDefaultTemplateAsync_Exists_ReturnsDefault()
    {
        // Arrange
        var defaultTemplate = new ModeloReporte
        {
            Nombre = "Default Template",
            ContenidoMarkdown = "# Default",
            Activo = true,
            EsDefault = true
        };

        var otherTemplate = new ModeloReporte
        {
            Nombre = "Other Template",
            ContenidoMarkdown = "# Other",
            Activo = true,
            EsDefault = false
        };

        _context.ModelosReporte.AddRange(defaultTemplate, otherTemplate);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.GetDefaultTemplateAsync();

        // Assert
        result.Should().NotBeNull();
        result!.Nombre.Should().Be("Default Template");
        result.EsDefault.Should().BeTrue();
    }

    [Fact(DisplayName = "T084: CreateTemplateAsync should create new template")]
    public async Task CreateTemplateAsync_ValidData_CreatesTemplate()
    {
        // Arrange
        var service = CreateService();
        var dto = new CreateTemplateDto
        {
            Nombre = "New Template",
            Descripcion = "New Description",
            ContenidoMarkdown = "# New Content",
            EsDefault = false
        };

        // Act
        var result = await service.CreateTemplateAsync(dto, Guid.NewGuid());

        // Assert
        result.Should().NotBeNull();
        result.Nombre.Should().Be("New Template");
        result.Descripcion.Should().Be("New Description");

        var dbTemplate = await _context.ModelosReporte.FindAsync(result.Id);
        dbTemplate.Should().NotBeNull();
    }

    [Fact(DisplayName = "T084: CreateTemplateAsync should clear other defaults when EsDefault is true")]
    public async Task CreateTemplateAsync_SetAsDefault_ClearsOtherDefaults()
    {
        // Arrange
        var existingDefault = new ModeloReporte
        {
            Nombre = "Existing Default",
            ContenidoMarkdown = "#",
            Activo = true,
            EsDefault = true
        };
        _context.ModelosReporte.Add(existingDefault);
        await _context.SaveChangesAsync();

        var service = CreateService();
        var dto = new CreateTemplateDto
        {
            Nombre = "New Default",
            ContenidoMarkdown = "#",
            EsDefault = true
        };

        // Act
        await service.CreateTemplateAsync(dto, Guid.NewGuid());

        // Assert
        var templates = await _context.ModelosReporte.ToListAsync();
        templates.Count(t => t.EsDefault).Should().Be(1);
        templates.First(t => t.EsDefault).Nombre.Should().Be("New Default");
    }

    [Fact(DisplayName = "T084: UpdateTemplateAsync should update template")]
    public async Task UpdateTemplateAsync_ValidData_UpdatesTemplate()
    {
        // Arrange
        var template = new ModeloReporte
        {
            Nombre = "Original",
            ContenidoMarkdown = "# Original",
            Activo = true
        };
        _context.ModelosReporte.Add(template);
        await _context.SaveChangesAsync();

        var service = CreateService();
        var dto = new UpdateTemplateDto
        {
            Nombre = "Updated",
            ContenidoMarkdown = "# Updated",
            Activo = true
        };

        // Act
        var result = await service.UpdateTemplateAsync(template.Id, dto, Guid.NewGuid());

        // Assert
        result.Should().NotBeNull();
        result!.Nombre.Should().Be("Updated");
        result.ContenidoMarkdown.Should().Be("# Updated");
    }

    [Fact(DisplayName = "T084: DeleteTemplateAsync should soft delete when in use")]
    public async Task DeleteTemplateAsync_InUse_SoftDeletes()
    {
        // Arrange
        var template = new ModeloReporte
        {
            Nombre = "In Use Template",
            ContenidoMarkdown = "#",
            Activo = true,
            EsDefault = true
        };
        _context.ModelosReporte.Add(template);
        await _context.SaveChangesAsync();

        var report = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow,
            FechaFin = DateTime.UtcNow,
            ContenidoMarkdown = "#",
            Estadisticas = "{}",
            ModeloReporteId = template.Id
        };
        _context.ReportesAutomatizados.Add(report);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.DeleteTemplateAsync(template.Id);

        // Assert
        result.Should().BeTrue();
        var dbTemplate = await _context.ModelosReporte.FindAsync(template.Id);
        dbTemplate.Should().NotBeNull();
        dbTemplate!.Activo.Should().BeFalse();
        dbTemplate.EsDefault.Should().BeFalse();
    }

    [Fact(DisplayName = "T084: DeleteTemplateAsync should hard delete when not in use")]
    public async Task DeleteTemplateAsync_NotInUse_HardDeletes()
    {
        // Arrange
        var template = new ModeloReporte
        {
            Nombre = "Unused Template",
            ContenidoMarkdown = "#",
            Activo = true
        };
        _context.ModelosReporte.Add(template);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.DeleteTemplateAsync(template.Id);

        // Assert
        result.Should().BeTrue();
        var dbTemplate = await _context.ModelosReporte.FindAsync(template.Id);
        dbTemplate.Should().BeNull();
    }

    [Fact(DisplayName = "T084: SetDefaultTemplateAsync should set template as default")]
    public async Task SetDefaultTemplateAsync_ValidTemplate_SetsAsDefault()
    {
        // Arrange
        var template1 = new ModeloReporte
        {
            Nombre = "Template 1",
            ContenidoMarkdown = "#",
            Activo = true,
            EsDefault = true
        };

        var template2 = new ModeloReporte
        {
            Nombre = "Template 2",
            ContenidoMarkdown = "#",
            Activo = true,
            EsDefault = false
        };

        _context.ModelosReporte.AddRange(template1, template2);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.SetDefaultTemplateAsync(template2.Id);

        // Assert
        result.Should().BeTrue();
        var templates = await _context.ModelosReporte.ToListAsync();
        templates.First(t => t.Id == template1.Id).EsDefault.Should().BeFalse();
        templates.First(t => t.Id == template2.Id).EsDefault.Should().BeTrue();
    }

    [Fact(DisplayName = "T084: SetDefaultTemplateAsync should return false for inactive template")]
    public async Task SetDefaultTemplateAsync_InactiveTemplate_ReturnsFalse()
    {
        // Arrange
        var template = new ModeloReporte
        {
            Nombre = "Inactive",
            ContenidoMarkdown = "#",
            Activo = false
        };
        _context.ModelosReporte.Add(template);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.SetDefaultTemplateAsync(template.Id);

        // Assert
        result.Should().BeFalse();
    }

    #endregion

    #region Statistics Tests

    [Fact(DisplayName = "T084: CalculateStatisticsAsync should count only delivered reports")]
    public async Task CalculateStatisticsAsync_OnlyDeliveredReports_Counted()
    {
        // Arrange
        var zona = await CreateTestZona();
        await CreateTestReport(estado: 1, zona: zona); // Delivered
        await CreateTestReport(estado: 1, zona: zona); // Delivered
        await CreateTestReport(estado: 0, zona: zona); // Draft - should not be counted

        var service = CreateService();

        // Act
        var result = await service.CalculateStatisticsAsync(
            DateTime.UtcNow.AddDays(-1),
            DateTime.UtcNow.AddDays(1));

        // Assert
        result.TotalReportes.Should().Be(2);
        result.ReportesEntregados.Should().Be(2);
        result.ReportesBorrador.Should().Be(0); // Borradores no se cuentan
    }

    [Fact(DisplayName = "T084: CalculateStatisticsAsync should group by delito")]
    public async Task CalculateStatisticsAsync_GroupsByDelito()
    {
        // Arrange
        var zona = await CreateTestZona();
        await CreateTestReport(estado: 1, zona: zona, delito: "Robo");
        await CreateTestReport(estado: 1, zona: zona, delito: "Robo");
        await CreateTestReport(estado: 1, zona: zona, delito: "Asalto");

        var service = CreateService();

        // Act
        var result = await service.CalculateStatisticsAsync(
            DateTime.UtcNow.AddDays(-1),
            DateTime.UtcNow.AddDays(1));

        // Assert
        result.PorDelito.Should().ContainKey("Robo");
        result.PorDelito["Robo"].Should().Be(2);
        result.PorDelito["Asalto"].Should().Be(1);
        result.DelitoMasFrecuente.Should().Be("Robo");
    }

    [Fact(DisplayName = "T084: CalculateStatisticsAsync should group by zona")]
    public async Task CalculateStatisticsAsync_GroupsByZona()
    {
        // Arrange
        var zona1 = await CreateTestZona("Zona Norte");
        var zona2 = await CreateTestZona("Zona Sur");
        await CreateTestReport(estado: 1, zona: zona1);
        await CreateTestReport(estado: 1, zona: zona1);
        await CreateTestReport(estado: 1, zona: zona2);

        var service = CreateService();

        // Act
        var result = await service.CalculateStatisticsAsync(
            DateTime.UtcNow.AddDays(-1),
            DateTime.UtcNow.AddDays(1));

        // Assert
        result.PorZona.Should().ContainKey("Zona Norte");
        result.PorZona["Zona Norte"].Should().Be(2);
        result.PorZona["Zona Sur"].Should().Be(1);
        result.ZonaMasActiva.Should().Be("Zona Norte");
    }

    [Fact(DisplayName = "T084: CalculateStatisticsAsync should count vulnerable populations")]
    public async Task CalculateStatisticsAsync_CountsVulnerablePopulations()
    {
        // Arrange
        var zona = await CreateTestZona();

        var report1 = new ReporteIncidencia
        {
            HechosReportados = "Test",
            AccionesRealizadas = "Test",
            Delito = "Test",
            Estado = 1,
            Sexo = "Mujer",
            Edad = 30,
            TipoDeAtencion = "Presencial",
            TipoDeAccion = "Preventiva",
            Zona = zona,
            LgbtttiqPlus = true,
            Migrante = false,
            SituacionCalle = true,
            Discapacidad = false,
            Traslados = "No",
            CreatedAt = DateTime.UtcNow
        };

        var report2 = new ReporteIncidencia
        {
            HechosReportados = "Test",
            AccionesRealizadas = "Test",
            Delito = "Test",
            Estado = 1,
            Sexo = "Mujer",
            Edad = 30,
            TipoDeAtencion = "Presencial",
            TipoDeAccion = "Preventiva",
            Zona = zona,
            LgbtttiqPlus = false,
            Migrante = true,
            SituacionCalle = false,
            Discapacidad = true,
            Traslados = "Sí",
            CreatedAt = DateTime.UtcNow
        };

        _context.ReportesIncidencia.AddRange(report1, report2);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.CalculateStatisticsAsync(
            DateTime.UtcNow.AddDays(-1),
            DateTime.UtcNow.AddDays(1));

        // Assert
        result.TotalLgbtttiq.Should().Be(1);
        result.TotalMigrantes.Should().Be(1);
        result.TotalSituacionCalle.Should().Be(1);
        result.TotalDiscapacidad.Should().Be(1);
        result.ConTraslado.Should().Be(1);
        result.SinTraslado.Should().Be(1);
    }

    [Fact(DisplayName = "T084: CalculateStatisticsAsync should group by age range")]
    public async Task CalculateStatisticsAsync_GroupsByAgeRange()
    {
        // Arrange
        var zona = await CreateTestZona();
        await CreateTestReport(estado: 1, zona: zona, edad: 15);  // Menor de 18
        await CreateTestReport(estado: 1, zona: zona, edad: 20);  // 18-24
        await CreateTestReport(estado: 1, zona: zona, edad: 30);  // 25-34
        await CreateTestReport(estado: 1, zona: zona, edad: 50);  // 45-54
        await CreateTestReport(estado: 1, zona: zona, edad: 70);  // 65+

        var service = CreateService();

        // Act
        var result = await service.CalculateStatisticsAsync(
            DateTime.UtcNow.AddDays(-1),
            DateTime.UtcNow.AddDays(1));

        // Assert
        result.PorRangoEdad.Should().ContainKey("Menor de 18");
        result.PorRangoEdad.Should().ContainKey("18-24");
        result.PorRangoEdad.Should().ContainKey("25-34");
        result.PorRangoEdad.Should().ContainKey("45-54");
        result.PorRangoEdad.Should().ContainKey("65+");
    }

    #endregion

    #region DeleteReportAsync Tests

    [Fact(DisplayName = "T084: DeleteReportAsync should return false when report not found")]
    public async Task DeleteReportAsync_NotFound_ReturnsFalse()
    {
        // Arrange
        var service = CreateService();

        // Act
        var result = await service.DeleteReportAsync(999);

        // Assert
        result.Should().BeFalse();
    }

    [Fact(DisplayName = "T084: DeleteReportAsync should delete report")]
    public async Task DeleteReportAsync_Exists_DeletesReport()
    {
        // Arrange
        var report = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow,
            FechaFin = DateTime.UtcNow,
            ContenidoMarkdown = "#",
            Estadisticas = "{}"
        };
        _context.ReportesAutomatizados.Add(report);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.DeleteReportAsync(report.Id);

        // Assert
        result.Should().BeTrue();
        var dbReport = await _context.ReportesAutomatizados.FindAsync(report.Id);
        dbReport.Should().BeNull();
    }

    #endregion

    #region SendReportByEmailAsync Tests

    [Fact(DisplayName = "T084: SendReportByEmailAsync should return false when report not found")]
    public async Task SendReportByEmailAsync_NotFound_ReturnsFalse()
    {
        // Arrange
        var service = CreateService();

        // Act
        var result = await service.SendReportByEmailAsync(999, new List<string> { "test@test.com" });

        // Assert
        result.Should().BeFalse();
    }

    [Fact(DisplayName = "T084: SendReportByEmailAsync should send email and update report")]
    public async Task SendReportByEmailAsync_Success_UpdatesReport()
    {
        // Arrange
        var report = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow.AddDays(-1),
            FechaFin = DateTime.UtcNow,
            ContenidoMarkdown = "# Test Report",
            Estadisticas = "{}",
            Enviado = false
        };
        _context.ReportesAutomatizados.Add(report);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.SendReportByEmailAsync(
            report.Id,
            new List<string> { "recipient@test.com" });

        // Assert
        result.Should().BeTrue();

        var dbReport = await _context.ReportesAutomatizados.FindAsync(report.Id);
        dbReport!.Enviado.Should().BeTrue();
        dbReport.FechaEnvio.Should().NotBeNull();
        dbReport.ErrorMensaje.Should().BeNull();

        _mockEmailService.Verify(
            s => s.SendAsync(It.Is<SendEmailRequestDto>(r =>
                r.Recipients.Contains("recipient@test.com") &&
                r.Subject.Contains("Reporte de Incidencias")),
                It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact(DisplayName = "T084: SendReportByEmailAsync should store error on failure")]
    public async Task SendReportByEmailAsync_Failure_StoresError()
    {
        // Arrange
        _mockEmailService.Setup(s => s.SendAsync(
                It.IsAny<SendEmailRequestDto>(),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(new SendEmailResultDto
            {
                Success = false,
                Error = "SMTP connection failed"
            });

        var report = new ReporteAutomatizado
        {
            FechaInicio = DateTime.UtcNow,
            FechaFin = DateTime.UtcNow,
            ContenidoMarkdown = "#",
            Estadisticas = "{}",
            Enviado = false
        };
        _context.ReportesAutomatizados.Add(report);
        await _context.SaveChangesAsync();

        var service = CreateService();

        // Act
        var result = await service.SendReportByEmailAsync(
            report.Id,
            new List<string> { "test@test.com" });

        // Assert
        result.Should().BeFalse();

        var dbReport = await _context.ReportesAutomatizados.FindAsync(report.Id);
        dbReport!.Enviado.Should().BeFalse();
        dbReport.ErrorMensaje.Should().Be("SMTP connection failed");
    }

    #endregion

    #region Configuration Tests

    [Fact(DisplayName = "T084: GetConfigurationAsync should return configuration from settings")]
    public async Task GetConfigurationAsync_ReturnsConfiguration()
    {
        // Arrange
        _mockConfiguration.Setup(c => c["AutomatedReports:GenerationTime"]).Returns("08:00:00");
        _mockConfiguration.Setup(c => c["AutomatedReports:Enabled"]).Returns("true");

        // Use helper to properly mock IConfigurationSection for Get<List<string>>()
        var mockSection = CreateMockListSection(new List<string> { "test@test.com" });
        _mockConfiguration.Setup(c => c.GetSection("AutomatedReports:Recipients")).Returns(mockSection.Object);

        var service = CreateService();

        // Act
        var result = await service.GetConfigurationAsync();

        // Assert
        result.GenerationTime.Should().Be(new TimeSpan(8, 0, 0));
        result.Enabled.Should().BeTrue();
        result.Recipients.Should().ContainSingle().Which.Should().Be("test@test.com");
    }

    [Fact(DisplayName = "T084: GetConfigurationAsync should return defaults when not configured")]
    public async Task GetConfigurationAsync_NoConfig_ReturnsDefaults()
    {
        // Arrange
        _mockConfiguration.Setup(c => c["AutomatedReports:GenerationTime"]).Returns((string?)null);
        _mockConfiguration.Setup(c => c["AutomatedReports:Enabled"]).Returns((string?)null);

        // Use helper to properly mock empty IConfigurationSection
        var mockSection = CreateMockListSection(null);
        _mockConfiguration.Setup(c => c.GetSection("AutomatedReports:Recipients")).Returns(mockSection.Object);

        var service = CreateService();

        // Act
        var result = await service.GetConfigurationAsync();

        // Assert
        result.GenerationTime.Should().Be(new TimeSpan(6, 0, 0)); // Default
        result.Enabled.Should().BeFalse();
        result.Recipients.Should().BeEmpty();
    }

    #endregion

    #region GenerateReportAsync Tests

    [Fact(DisplayName = "T084: GenerateReportAsync should create report with statistics")]
    public async Task GenerateReportAsync_CreatesReportWithStatistics()
    {
        // Arrange
        var zona = await CreateTestZona();
        await CreateTestReport(estado: 1, zona: zona);
        await CreateTestReport(estado: 1, zona: zona);

        var service = CreateService();
        var request = new GenerateReportRequestDto
        {
            FechaInicio = DateTime.UtcNow.AddDays(-1),
            FechaFin = DateTime.UtcNow.AddDays(1),
            EnviarEmail = false
        };

        // Act
        var result = await service.GenerateReportAsync(request, Guid.NewGuid());

        // Assert
        result.Should().NotBeNull();
        result.Estadisticas.TotalReportes.Should().Be(2);
        result.ContenidoMarkdown.Should().Contain("Reporte");

        // Verify AI service was called
        _mockAiService.Verify(
            s => s.GenerateNarrativeAsync(
                It.Is<NarrativeRequestDto>(r => r.Statistics.TotalReportes == 2),
                It.IsAny<CancellationToken>()),
            Times.Once);

        // Verify audit was logged
        _mockAuditService.Verify(
            s => s.LogAsync(
                AuditCodes.AUTO_REPORT_GEN,
                It.IsAny<int?>(),
                "ReporteAutomatizado",
                It.IsAny<string?>(),
                It.IsAny<string?>(),
                It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact(DisplayName = "T084: GenerateReportAsync should use template when specified")]
    public async Task GenerateReportAsync_WithTemplate_UsesTemplate()
    {
        // Arrange
        var template = new ModeloReporte
        {
            Nombre = "Custom Template",
            ContenidoMarkdown = "# Custom\n{{fecha_inicio}} - {{fecha_fin}}\n{{narrativa_ia}}",
            Activo = true
        };
        _context.ModelosReporte.Add(template);
        await _context.SaveChangesAsync();

        var service = CreateService();
        var request = new GenerateReportRequestDto
        {
            FechaInicio = DateTime.UtcNow.AddDays(-1),
            FechaFin = DateTime.UtcNow.AddDays(1),
            ModeloReporteId = template.Id,
            EnviarEmail = false
        };

        // Act
        var result = await service.GenerateReportAsync(request, Guid.NewGuid());

        // Assert
        result.Should().NotBeNull();
        result.ContenidoMarkdown.Should().Contain("Custom");
        result.ModeloReporteId.Should().Be(template.Id);
    }

    [Fact(DisplayName = "T084: GenerateReportAsync should send email when requested")]
    public async Task GenerateReportAsync_SendEmail_SendsEmail()
    {
        // Arrange
        var service = CreateService();
        var request = new GenerateReportRequestDto
        {
            FechaInicio = DateTime.UtcNow.AddDays(-1),
            FechaFin = DateTime.UtcNow.AddDays(1),
            EnviarEmail = true,
            EmailDestinatarios = new List<string> { "test@test.com" }
        };

        // Act
        await service.GenerateReportAsync(request, Guid.NewGuid());

        // Assert
        _mockEmailService.Verify(
            s => s.SendAsync(
                It.Is<SendEmailRequestDto>(r => r.Recipients.Contains("test@test.com")),
                It.IsAny<CancellationToken>()),
            Times.Once);
    }

    #endregion

    #region DTO Structure Tests

    [Fact(DisplayName = "T084: AutomatedReportListDto should have required properties")]
    public void AutomatedReportListDto_Structure_IsCorrect()
    {
        // Arrange & Act
        var dto = new AutomatedReportListDto();

        // Assert
        dto.Id.Should().Be(0);
        dto.Enviado.Should().BeFalse();
        dto.TieneError.Should().BeFalse();
    }

    [Fact(DisplayName = "T084: ReportStatisticsDto should have required properties")]
    public void ReportStatisticsDto_Structure_IsCorrect()
    {
        // Arrange & Act
        var dto = new ReportStatisticsDto();

        // Assert
        dto.TotalReportes.Should().Be(0);
        dto.PorSexo.Should().NotBeNull();
        dto.PorDelito.Should().NotBeNull();
        dto.PorZona.Should().NotBeNull();
        dto.PorRangoEdad.Should().NotBeNull();
    }

    [Fact(DisplayName = "T084: GenerateReportRequestDto should have required properties")]
    public void GenerateReportRequestDto_Structure_IsCorrect()
    {
        // Arrange & Act
        var dto = new GenerateReportRequestDto();

        // Assert
        dto.EnviarEmail.Should().BeFalse();
        dto.EmailDestinatarios.Should().BeNull();
        dto.ModeloReporteId.Should().BeNull();
    }

    #endregion
}
